---
default_timezone: ""
email_host: ""
email_port: "587"
email_user: ""
email_password: "{{vault_email_password}}"
opensubtitles_user: "{{vault_opensubtitles_user}}"
opensubtitles_password: "{{vault_opensubtitles_password}}"
omdb_apikey: "{{vault_omdb_apikey}}"
project_notification_email: ""