---
- name: Restart Filebeat
  community.general.docker_container:
    name: filebeat
    container_default_behavior: compatibility
    restart: yes
  listen: restart filebeat

- name: Restart Logstash
  community.general.docker_container:
    name: logstash
    container_default_behavior: compatibility
    restart: yes
  listen: restart logstash

- name: Restart Elasticsearch
  community.general.docker_container:
    name: elasticsearch
    container_default_behavior: compatibility
    restart: yes
  listen: restart elasticsearch

- name: Restart Kibana
  community.general.docker_container:
    name: kibana
    container_default_behavior: compatibility
    restart: yes
  listen: restart kibana
