---
- name: Ensure Photoprism Directories Exist
  file:
    path: "{{item}}"
    state: directory
  loop:
    - "{{project_directory}}/photoprism/data/config/photoprism"
    - "{{project_directory}}/photoprism/originals"
    - "{{project_directory}}/photoprism/import"
    - "{{project_directory}}/photoprism/data"
  tags: photoprism

- name: Ensure Photoprism Configuration Files Exist
  template:
    src: photoprism.env.j2
    dest: "{{project_directory}}/photoprism/data/config/photoprism/photoprism.env"
  notify: restart photoprism
  no_log: true
  tags: photoprism

- import_tasks: roles/mariadb/tasks/database_manager.yml
  vars:
    database_name: "{{photoprism_database}}"
    database_user: "{{photoprism_database_user}}"
    database_password: "{{photoprism_database_password}}"
  tags: photoprism

- name: Create Photoprism Docker Container
  community.general.docker_container:
    name: photoprism
    image: "photoprism/photoprism:{{photoprism_version}}"
    pull: yes
    hostname: photoprism
    container_default_behavior: compatibility
    network_mode: default
    restart_policy: unless-stopped
    env_file: "{{project_directory}}/photoprism/data/config/photoprism/photoprism.env"
    security_opts:
      - "seccomp=unconfined"
      - "apparmor=unconfined"
    networks:
      - name: proxy
    networks_cli_compatible: yes
    state: started
    volumes:
      - "{{project_directory}}/photoprism/originals:/photoprism/originals"
      - "{{project_directory}}/photoprism/import:/photoprism/import"
      - "{{project_directory}}/photoprism/data:/photoprism/storage"
    labels:
      traefik.http.routers.photoprism.entrypoints: "websecure"
      traefik.http.routers.photoprism.tls: "true"
      traefik.http.routers.photoprism.rule: "Host(`{{photo_tld}}`)"
      traefik.http.routers.photoprism.middlewares: "default-headers@file"
      traefik.http.routers.photoprism.service: "photoprism"
      traefik.http.services.photoprism.loadbalancer.server.port: "2342"
      traefik.enable: "true"
  tags: photoprism