---
wallabag_database_user: "wallabag"
wallabag_database_password: "{{vault_wallabag_database_password}}"
wallabag_database: "wallabag"
wallabag_database_class: "Wallabag\\CoreBundle\\Doctrine\\DBAL\\Driver\\CustomPostgreSQLDriver"
wallabag_admin_user: "wallabag"
wallabag_admin_passwword: "{{vault_wallabag_admin_passwword}}"