---
- name: Ensure MongoDB Directory Exist
  when: inventory_hostname == groups['workers'][0]
  ansible.builtin.file:
    path: "{{ project_root_directory }}/mongodb"
    mode: 0755
    state: directory
  tags: mongodb

- name: Deploy MongoDB Service
  when: inventory_hostname == groups['managers'][0]
  community.docker.docker_swarm_service:
    name: mongodb
    hostname: "{{ mongodb_hostname }}"
    image: "{{ mongodb_docker_image }}:{{ mongodb_version }}"
    networks:
      - "{{ traefik_network }}"
    mode: replicated
    force_update: yes
    restart_config:
      condition: on-failure
    publish:
      - target_port: "{{ mongodb_port }}"
        published_port: "{{ mongodb_port }}"
        protocol: "tcp"
        mode: "ingress"
    mounts:
      - source: "/greytalon/apps/mongodb/"
        target: /data/db/
        type: bind
    placement:
      constraints:
        - node.id == {{ greytalon_node_id }}
    replicas: 1
    state: present
  tags: mongodb