---
- name: Ensure Omada Data Volume Exist
  when: inventory_hostname == groups['managers'][0]
  docker_volume:
    name: omada-data
    state: present
  tags: omada

- name: Ensure Omada Work Volume Exist
  when: inventory_hostname == groups['managers'][0]
  docker_volume:
    name: omada-work
    state: present
  tags: omada

- name: Ensure Omada Logs Volume Exist
  when: inventory_hostname == groups['managers'][0]
  docker_volume:
    name: omada-logs
    state: present
  tags: omada

- name: Deploy Omada Service
  when: inventory_hostname == groups['managers'][0]
  community.docker.docker_swarm_service:
    name: omada
    hostname: "{{omada_hostname}}"
    image: "{{omada_docker_image}}:{{omada_version}}"
    networks:
      - "{{traefik_network}}"
    env:
      MANAGE_HTTP_PORT: "{{omada_port}}"
      MANAGE_HTTPS_PORT: "{{omada_secure_port}}"
      PGID: "{{omada_group}}"
      PORTAL_HTTP_PORT: "{{omada_port}}"
      PORTAL_HTTPS_PORT: "{{omada_secure_port}}"
      PUID: "{{omada_user}}"
      SHOW_SERVER_LOGS: "true"
      SHOW_MONGODB_LOGS: "false"
      TZ: "{{default_timezone}}"
    mode: global
    force_update: yes
    restart_config:
      condition: on-failure
    placement:
      constraints:
        - node.id == {{greytalon_node_id}}
    mounts:
      - source: omada-data
        target: /opt/tplink/EAPController/data/
        type: volume
      - source: omada-work
        target: /opt/tplink/EAPController/work/
        type: volume
      - source: omada-logs
        target: /opt/tplink/EAPController/logs/
        type: volume
    labels:
      traefik.http.routers.omada.rule: "Host(`omada.{{project_tld}}`)"
      traefik.http.routers.omada.entrypoints: "websecure"
      traefik.http.routers.omada.tls: "true"
      traefik.http.routers.omada.service: "omada"
      traefik.http.routers.omada.tls.certresolver: "{{default_certificate_resolver}}"
      traefik.http.services.omada.loadbalancer.server.port: "{{omada_secure_port}}"
      traefik.http.middlewares.omada-middlewares.chain.middlewares: "omada-redirect,omada-headers"
      traefik.http.middlewares.omada-headers.headers.customrequestheaders.Host: "omada.{{project_tld}}:8043"
      traefik.http.middlewares.omada-headers.headers.customresponseheaders.Host: "omada.{{project_tld}}"
      traefik.http.middlewares.omada-redirect.redirectregex.regex: "^https:\\/\\/([^\\/]+)\\/?$$"
      traefik.http.middlewares.omada-redirect.redirectregex.replacement: "https://omada.{{project_tld}}/login"
      traefik.http.routers.omada.middlewares: "omada-middlewares"
      traefik.http.services.omada.loadbalancer.server.scheme: "https"
      traefik.http.services.omada.loadbalancer.passhostheader: "true"
      traefik.enable: "true"
    state: present
  tags: omada