---
- name: Restart Matrix
  community.general.docker_container:
    name: synapse
    container_default_behavior: compatibility
    restart: yes
  listen: restart matrix

- name: Restart Turn Server
  community.general.docker_container:
    name: coturn
    container_default_behavior: compatibility
    restart: yes
  listen: restart coturn

- name: Restart Identity Server
  community.general.docker_container:
    name: mxisd
    container_default_behavior: compatibility
    restart: yes
  listen: restart mxisd

- name: Restart InspIRCd
  community.general.docker_container:
    name: inspircd
    container_default_behavior: compatibility
    restart: yes
  listen: restart inspircd

- name: Restart IRC Bridge
  community.general.docker_container:
    name: irc-bridge
    container_default_behavior: compatibility
    restart: yes
  listen: restart irc-bridge
