---
- name: Ensure Alert Manager Directory Exist
  when: inventory_hostname == groups['managers'][0]
  file:
    path: "{{project_root_directory}}/grafana/alertmanager"
    state: directory
  tags: alertmanager

- name: Ensure Alert Manager Configuration File Exist
  when: inventory_hostname == groups['managers'][0]
  template:
    src: alertmanager.yml.j2
    dest: "{{project_root_directory}}/grafana/alertmanager/config.yml"
  no_log: true
  tags: alertmanager

- name: Deploy Alert Manager Service
  when: inventory_hostname == groups['managers'][0]
  community.docker.docker_swarm_service:
    name: alertmanager
    hostname: "{{alertmanager_hostname}}"
    image: "{{alertmanager_docker_image}}:{{grafana_stack_version}}"
    networks:
      - "{{traefik_network}}"
    mode: replicated
    force_update: yes
    restart_config:
      condition: on-failure
    placement:
      constraints:
        - node.id == pbe2hzwp9iaay6qop5yhmhhl1
    replicas: 1
    mounts:
      - source: /yellowtalon/apps/grafana/alertmanager/
        target: /etc/alertmanager/
        type: bind
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
      - '--cluster.advertise-address=127.0.0.1:9093'
      - '--web.listen-address=localhost:9093'
    state: present
  tags: alertmanager