---
- name: Deploy Cadvisor Service
  when: inventory_hostname == groups['managers'][0]
  community.docker.docker_swarm_service:
    name: cadvisor
    hostname: "{{cadvisor_hostname}}"
    image: "{{cadvisor_docker_image}}:{{grafana_stack_version}}"
    networks:
      - "{{traefik_network}}"
    mode: replicated
    force_update: yes
    restart_config:
      condition: on-failure
    placement:
      constraints:
        - node.id == {{yellowtalon_node_id}}
    replicas: 1
    mounts:
      - source: /
        target: /rootfs
        type: bind
      - source: /var/run/
        target: /var/run/
        type: bind
      - source: /sys/
        target: /sys/
        type: bind
      - source: /dev/disk/
        target: /dev/disk/
        type: bind
      - source: /var/lib/docker/
        target: /var/lib/docker/
        type: bind
    state: present
  tags: cadvisor