---
- name: Deploy Base Services
  hosts: all
  gather_facts: False
  become: yes
  roles:
    - traefik
    - homer
    - postgres
    - mariadb
    - redis
    - mongodb
    - prometheus
    - elasticsearch
    - authelia
    - mailrise
    - uptime_kuma
    - gitea
    - n8n
    - minio