---
- name: Deploy Base Services
  hosts: all
  gather_facts: False
  become: yes
  roles:
    - traefik
    - vault
    - homer
    - postgres
    - redis
    - mongodb
    - elasticsearch
    - authelia
    - gitea
    - portus
    - jenkins
    - n8n
    - minio