---
    - name: Restart CyberChef
      community.general.docker_container:
        name: cyberchef
        container_default_behavior: compatibility
        restart: yes
      listen: restart cyberchef
