---
- name: Restart LANcache DNS
  community.general.docker_container:
    name: lancache-dns
    container_default_behavior: compatibility
    restart: yes
  listen: restart lancache-dns

- name: Restart SNI Proxy
  community.general.docker_container:
    name: sniproxy
    container_default_behavior: compatibility
    restart: yes
  listen: restart sniproxy

- name: Restart Monolithic
  community.general.docker_container:
    name: monolithic
    container_default_behavior: compatibility
    restart: yes
  listen: restart monolithic