---
- name: Ensure Media Directory Exist
  when: inventory_hostname == groups['media'][0]
  file:
    path: "{{project_media_directory}}/music"
    state: directory
  tags: lidarr

- name: Deploy AMD Service
  when: inventory_hostname == groups['managers'][0]
  community.docker.docker_swarm_service:
    name: amd
    hostname: "{{amd_hostname}}"
    image: "{{amd_docker_image}}:{{amd_version}}"
    networks:
      - "{{traefik_network}}"
    env:
      PUID: "{{media_user}}"
      PGID: "{{media_group}}"
      AUTOSTART: "true"
      LIST: "both"
      DOWNLOADMODE: "wanted"
      FALLBACKSEARCH: "true"
      SCRIPTINTERVAL: "1h"
      SearchType: "both"
      Concurrency: "1"
      FORMAT: "FLAC"
      requirequality: "true"
      MatchDistance: "10"
      replaygain: "true"
      FolderPermissions: "766"
      FilePermissions: "666"
      MBRAINZMIRROR: "https://musicbrainz.org"
      MBRATELIMIT: "1"
      LidarrUrl: "{{lidarr_url}}"
      LidarrAPIkey: "{{lidarr_api_key}}"
      ARL_TOKEN: "{{lidarr_arl_token}}"
    mode: replicated
    force_update: yes
    restart_config:
      condition: on-failure
    placement:
      constraints:
        - node.id == o777re5ggyfs6gvyau96cpm2b
    mounts:
      - source: "/blacktalon/apps/lidarr/"
        target: /config/
        type: bind
      - source: "{{project_media_directory}}/music/"
        target: /downloads-amd/
        type: bind
    replicas: 1
    state: present
  tags: amd