---
- set_fact:
    mxisd_url_endpoint_public: "https://{{chat_tld}}/_matrix/identity/api/v1"

- name: Ensure Identity Server Volume Exist
  docker_volume:
    name: mxisd
    state: present
  notify: restart mxisd
  tags: matrix

- name: Ensure Matrix Identity Server Directories Exist
  file:
    path: "{{item}}"
    state: directory
  loop:
    - "{{project_directory}}/synapse/mxisd"
    - "{{project_directory}}/synapse/mxisd/etc"
    - "{{project_directory}}/synapse/mxisd/var"
  tags: matrix

- name: Ensure Identity Server Config Exist
  template:
    src: mxisd.yaml.j2
    dest: "{{project_directory}}/synapse/mxisd/etc/mxisd.yaml"
  no_log: true
  tags: matrix

- name: Ensure Email Templates Exist
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
  with_items:
    - {src: invite-template.eml.j2,dest: "{{project_directory}}/synapse/mxisd/var/invite-template.eml"}
    - {src: validate-template.eml.j2,dest: "{{project_directory}}/synapse/mxisd/var/validate-template.eml"}
    - {src: unbind-fraudulent.eml.j2,dest: "{{project_directory}}/synapse/mxisd/var/unbind-fraudulent.eml"}
    - {src: mxid-template.eml.j2,dest: "{{project_directory}}/synapse/mxisd/var/mxid-template.eml"}
  no_log: true
  tags: matrix

- name: Create Matrix Identity Server Container
  community.general.docker_container:
    name: mxisd
    image: "kamax/mxisd:{{matrix_version}}"
    pull: yes
    hostname: mxisd
    container_default_behavior: compatibility
    network_mode: default
    restart_policy: unless-stopped
    networks:
      - name: proxy
    networks_cli_compatible: yes
    state: started
    volumes:
      - "{{project_directory}}/synapse/mxisd/etc:/etc/mxisd"
      - "{{project_directory}}/synapse/mxisd/var:/var/mxisd"
      - mxisd:/mxisd
    labels:
      traefik.http.routers.mxisd.entrypoints: "websecure"
      traefik.http.routers.mxisd.tls: "true"
      traefik.http.routers.mxisd.rule: "Host(`id.{{chat_tld}}`)"
      traefik.http.routers.mxisd.middlewares: "default-headers@file"
      traefik.http.routers.mxisd.service: "mxisd"
      traefik.http.services.mxisd.loadbalancer.server.port: "8090"
      traefik.enable: "true"
  tags: matrix