---
- name: Ensure Wizarr Directories Exist
  when: inventory_hostname == ['redtalon'][0]
  ansible.builtin.file:
    path: /redtalon/apps/wizarr
    mode: 0755
    state: directory
  tags: wizarr

- name: Ensure Wizarr DNS Records Exist
  ansible.builtin.import_tasks: roles/traefik/tasks/dreamhost.yml
  when: inventory_hostname == groups['managers'][0]
  vars:
    domain_name: "{{ wizarr_domain }}"
  tags:
    - wizarr
    - dns
  no_log: true

- name: Deploy Wizarr Service
  when: inventory_hostname == groups['managers'][0]
  community.docker.docker_swarm_service:
    name: wizarr
    hostname: "{{ wizarr_hostname }}"
    image: "{{ wizarr_docker_image }}:{{ wizarr_version }}"
    networks:
      - "{{ traefik_network }}"
    mode: replicated
    force_update: yes
    restart_config:
      condition: on-failure
    placement:
      constraints:
        - node.id == {{ redtalon_node_id }}
    replicas: 1
    mounts:
      - source: /redtalon/apps/wizarr/
        target: /data/database/
        type: bind
    labels:
      traefik.http.routers.wizarr.entrypoints: "websecure"
      traefik.http.routers.wizarr.rule: "Host(`{{ wizarr_domain }}`)"
      traefik.http.routers.wizarr.middlewares: "default-headers@file"
      traefik.http.routers.wizarr.tls: "true"
      traefik.http.routers.wizarr.service: "wizarr"
      traefik.http.routers.wizarr.tls.certresolver: "{{ default_certificate_resolver }}"
      traefik.http.services.wizarr.loadbalancer.server.port: "{{ wizarr_port }}"
      traefik.enable: "true"
    state: present
  tags: wizarr