---
- name: Ensure Mailrise Directory Exist
  when: inventory_hostname == groups['managers'][0]
  file:
    path: "{{project_root_directory}}/mailrise/"
    state: directory
  tags: mailrise

- name: Ensure Mailrise Configuration Files Exist
  when: inventory_hostname == groups['managers'][0]
  template:
    src: mailrise.conf.j2
    dest: "{{project_root_directory}}/mailrise/mailrise.conf"
  tags: mailrise
  no_log: true

- name: Deploy Mailrise Service
  when: inventory_hostname == groups['managers'][0]
  community.docker.docker_swarm_service:
    name: mailrise
    hostname: "{{mailrise_hostname}}"
    image: "{{mailrise_docker_image}}:{{mailrise_version}}"
    networks:
      - "{{traefik_network}}"
    mode: global
    force_update: yes
    restart_config:
      condition: on-failure
    placement:
      constraints:
        - node.id == {{yellowtalon_node_id}}
    mounts:
      - source: "{{project_root_directory}}/mailrise/mailrise.conf"
        target: /etc/mailrise.conf
        type: bind
    state: present
  tags: mailrise