---
mastodon_site_name: "{{ vault_mastodon_site_name }}"
mastodon_database_user: "{{ vault_mastodon_database_user }}"
mastodon_database_password: "{{ vault_mastodon_database_password }}"
mastodon_database: "{{ vault_mastodon_database }}"
mastodon_secret_key_base: "{{ vault_mastodon_secret_key_base }}"
mastodon_otp_secret: "{{ vault_mastodon_otp_secret }}"
mastodon_vapid_private_key: "{{ vault_mastodon_vapid_private_key }}"
mastodon_vapid_public_key: "{{ vault_mastodon_vapid_public_key }}"