---
- name: Ensure Readarr Media Dataset Exist
  when: inventory_hostname == groups['media'][0]
  community.general.zfs:
    name: blacktalon/media/books
    state: present
  tags:
    - readarr
    - zfs

- name: Ensure Readarr Media Download Dataset Exist
  when: inventory_hostname == groups['media'][0]
  community.general.zfs:
    name: blacktalon/media/downloads/books
    state: present
  tags:
    - readarr
    - zfs

- name: Ensure Readarr Dataset Exist
  when: inventory_hostname == groups['media'][0]
  community.general.zfs:
    name: blacktalon/apps/readarr2
    state: present
  tags:
    - readarr
    - zfs

- name: Ensure Readarr DNS Records Exist
  ansible.builtin.import_tasks: roles/traefik/tasks/dreamhost.yml
  when: inventory_hostname == groups['managers'][0]
  vars:
    domain_name: "{{ readarr2_domain }}"
  tags:
    - readarr
    - dns
  no_log: true

- name: Ensure Readarr Configuration Files Exist
  when: inventory_hostname == groups['media'][0]
  ansible.builtin.template:
    src: books_config.xml.j2
    mode: 0644
    dest: "{{ project_root_directory }}/readarr2/config.xml"
  tags: readarr
  no_log: true

- name: Deploy Readarr Service
  when: inventory_hostname == groups['managers'][0]
  community.docker.docker_swarm_service:
    name: readarr2
    hostname: "{{ readarr2_hostname }}"
    image: "{{ readarr_docker_image }}:{{ readarr_version }}"
    networks:
      - "{{ traefik_network }}"
    mode: replicated
    force_update: yes
    restart_config:
      condition: on-failure
    env:
      PUID: "{{ media_user }}"
      PGID: "{{ media_group }}"
      TZ: "{{ default_timezone }}"
      DOCKER_MODS: "gilbn/theme.park:{{ readarr2_hostname }}"
      TP_THEME: "{{ theme_park_default }}"
    placement:
      constraints:
        - node.id == {{ blacktalon_node_id }}
    replicas: 1
    mounts:
      - source: "/blacktalon/apps/readarr2/"
        target: /config/
        type: bind
      - source: "{{ project_media_directory }}/books/"
        target: /media/books/
        type: bind
      - source: "{{ project_download_directory }}"
        target: /media/downloads/
        type: bind
    labels:
      traefik.http.routers.readarr2.entrypoints: "websecure"
      traefik.http.routers.readarr2.rule: "Host(`{{ readarr2_domain }}`)"
      traefik.http.routers.readarr2.middlewares: "default-headers@file,authelia@file"
      traefik.http.routers.readarr2.tls: "true"
      traefik.http.routers.readarr2.service: "readarr2"
      traefik.http.routers.readarr2.tls.certresolver: "{{ default_certificate_resolver }}"
      traefik.http.services.readarr2.loadbalancer.server.port: "{{ readarr_port }}"
      traefik.enable: "true"
    state: present
  tags: readarr