---
- name: Import Readarr Audiobooks Role
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/audiobooks.yml"
  tags: readarr

- name: Import Readarr Books Role
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/books.yml"
  tags: readarr