---
- name: Restart Firefly
  community.general.docker_container:
    name: firefly
    container_default_behavior: compatibility
    restart: yes
  listen: restart firefly

- name: Restart Firefly Importer
  community.general.docker_container:
    name: firefly-importer
    container_default_behavior: compatibility
    restart: yes
  listen: restart firefly-importer