---
- name: Ensure n8n Databases Exist
  ansible.builtin.import_tasks: roles/postgres/tasks/database_manager.yml
  when: inventory_hostname == groups['managers'][0]
  vars:
    database_name: "{{ n8n_database }}"
    database_user: "{{ n8n_database_user }}"
    database_password: "{{ n8n_database_password }}"
  tags: n8n
  no_log: false

- name: Deploy n8n Service
  when: inventory_hostname == groups['managers'][0]
  community.docker.docker_swarm_service:
    name: n8n
    hostname: "{{ n8n_hostname }}"
    image: "{{ n8n_docker_image }}:{{ n8n_version }}"
    networks:
      - "{{ traefik_network }}"
    env:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: "{{ postgres_hostname }}"
      DB_POSTGRESDB_PORT: "{{ postgres_port }}"
      DB_POSTGRESDB_DATABASE: "{{ n8n_database }}"
      DB_POSTGRESDB_USER: "{{ n8n_database_user }}"
      DB_POSTGRESDB_PASSWORD: "{{ n8n_database_password }}"
      N8N_EDITOR_BASE_URL: "n8n.{{ project_tld }}"
      N8N_EMAIL_MODE: "smtp"
      N8N_SMTP_HOST: "{{ email_host }}"
      N8N_SMTP_PORT: "{{ email_port }}"
      N8N_SMTP_USER: "{{ email_user }}"
      N8N_SMTP_PASS: "{{ email_password }}"
      N8N_SMTP_SENDER: "{{ email_user }}"
      N8N_SMTP_SSL: "true"
      GENERIC_TIMEZONE: "{{ default_timezone }}"
      N8N_BASIC_AUTH_ACTIVE: "true"
      N8N_BASIC_AUTH_USER: "{{ n8n_default_user }}"
      N8N_BASIC_AUTH_PASSWORD: "{{ n8n_default_password }}"
    mode: replicated
    force_update: yes
    restart_config:
      condition: on-failure
    placement:
      constraints:
        - node.id == {{ greytalon_node_id }}
    replicas: 1
    labels:
      traefik.http.routers.n8n.entrypoints: "websecure"
      traefik.http.routers.n8n.rule: "Host(`n8n.{{ project_tld }}`)"
      traefik.http.routers.n8n.middlewares: "default-headers@file"
      traefik.http.routers.n8n.tls: "true"
      traefik.http.routers.n8n.service: "n8n"
      traefik.http.routers.n8n.tls.certresolver: "{{ default_certificate_resolver }}"
      traefik.http.services.n8n.loadbalancer.server.port: "{{ n8n_port }}"
      traefik.enable: "true"
    state: present
  tags: n8n