---
- name: Ensure Media Datasets Exist
  when: inventory_hostname == groups['media'][0]
  community.general.zfs:
    name: blacktalon/media/movies-uhd
    state: present
  tags:
    - radarr-uhd
    - zfs

- name: Ensure Media Download Datasets Exist
  when: inventory_hostname == groups['media'][0]
  community.general.zfs:
    name: blacktalon/media/downloads/movies-uhd
    state: present
  tags:
    - radarr-uhd
    - zfs

- name: Ensure Radarr UHD Dataset Exist
  when: inventory_hostname == groups['media'][0]
  community.general.zfs:
    name: blacktalon/apps/radarr2
    state: present
  tags:
    - radarr-uhd
    - zfs

- name: Ensure Readarr UHD DNS Records Exist
  ansible.builtin.import_tasks: roles/traefik/tasks/dreamhost.yml
  when: inventory_hostname == groups['managers'][0]
  vars:
    domain_name: "{{ radarr_uhd_domain }}"
  tags:
    - readarr-uhd
    - dns
  no_log: true

- name: Ensure Radarr UHD Configuration Files Exist
  when: inventory_hostname == groups['media'][0]
  ansible.builtin.template:
    src: config-uhd.xml.j2
    mode: 0644
    dest: "{{ project_root_directory }}/radarr2/config.xml"
  tags: radarr-uhd
  no_log: true

- name: Deploy Radarr UHD Service
  when: inventory_hostname == groups['managers'][0]
  community.docker.docker_swarm_service:
    name: radarr_uhd
    hostname: "{{ radarr_uhd_hostname }}"
    image: "{{ radarr_docker_image }}:{{ radarr_version }}"
    networks:
      - "{{ traefik_network }}"
    mode: replicated
    force_update: yes
    restart_config:
      condition: on-failure
    env:
      PUID: "{{ media_user }}"
      PGID: "{{ media_group }}"
      TZ: "{{ default_timezone }}"
      DOCKER_MODS: "gilbn/theme.park:{{ radarr_hostname }}"
      TP_THEME: "{{ theme_park_default }}"
    placement:
      constraints:
        - node.id == {{ blacktalon_node_id }}
    replicas: 1
    mounts:
      - source: "/blacktalon/apps/radarr2/"
        target: /config/
        type: bind
      - source: "{{ project_media_directory }}/movies-uhd/"
        target: /media/movies-uhd/
        type: bind
      - source: "{{ project_download_directory }}"
        target: /media/downloads/
        type: bind
    labels:
      traefik.http.routers.radarr-uhd.entrypoints: "websecure"
      traefik.http.routers.radarr-uhd.rule: "Host(`{{ radarr_uhd_domain }}`)"
      traefik.http.routers.radarr-uhd.middlewares: "default-headers@file,authelia@file"
      traefik.http.routers.radarr-uhd.tls: "true"
      traefik.http.routers.radarr-uhd.service: "radarr-uhd"
      traefik.http.routers.radarr-uhd.tls.certresolver: "{{ default_certificate_resolver }}"
      traefik.http.services.radarr-uhd.loadbalancer.server.port: "{{ radarr_uhd_port }}"
      traefik.enable: "true"
    state: present
  tags: radarr-uhd