---
- name: Restart Guacd
  community.general.docker_container:
    name: guacd
    container_default_behavior: compatibility
    restart: yes
  listen: restart gucad

- name: Restart Guacamole
  community.general.docker_container:
    name: guacamole
    container_default_behavior: compatibility
    restart: yes
  listen: restart guacamole
