---
- name: Deploy Clair Service
  when: inventory_hostname == groups['managers'][0]
  community.docker.docker_swarm_service:
    name: portus-background
    hostname: "{{portus_background_hostname}}"
    image: "{{portus_docker_image}}:{{portus_version}}"
    networks:
      - "{{traefik_network}}"
    mode: replicated
    force_update: yes
    restart_config:
      condition: on-failure
    placement:
      constraints:
        - node.id == {{greytalon_node_id}}
    replicas: 1
    env:
      PORTUS_MACHINE_FQDN_VALUE: "hub.{{git_tld}}"
      CONFIG_PREFIX: "PORTUS"
      PORTUS_PASSWORD: "{{portus_user_password}}"
      PORTUS_SECRET_KEY_BASE: "{{portus_secret_key_base}}"
      PORTUS_KEY_PATH: "/certificates"
      PORTUS_DB_ADAPTER: "postgresql"
      PORTUS_DB_HOST: "{{postgres_hostname}}"
      PORTUS_DB_USERNAME: "{{portus_database_user}}"
      PORTUS_DB_PASSWORD: "{{portus_database_password}}"
      PORTUS_DB_DATABASE: "{{portus_database}}"
      PORTUS_DB_PORT: "{{postgres_port}}"
      PORTUS_BACKGROUND: "true"
      PORTUS_SECURITY_CLAIR_SERVER: "http://clair:6060"
    mounts:
      - source: /greytalon/apps/portus/data/
        target: /data/
        type: bind
    state: present
  tags: clair