---
- name: Deploy Clair Service
  when: inventory_hostname == groups['managers'][0]
  community.docker.docker_swarm_service:
    name: clair
    hostname: "{{clair_hostname}}"
    image: "{{clair_docker_image}}:{{clair_version}}"
    networks:
      - "{{traefik_network}}"
    mode: replicated
    force_update: yes
    restart_config:
      condition: on-failure
    placement:
      constraints:
        - node.id == m1enhyjtwu2k7zvvjbgwv2e4s
    replicas: 1
    mounts:
      - source: /greytalon/apps/portus/clair/clair.yml
        target: /etc/clair/config.yaml
        type: bind
      - source: /tmp/
        target: /tmp/
        type: bind
    state: present
  tags: clair