---
- name: Deploy Docker Registry Service
  when: inventory_hostname == groups['managers'][0]
  community.docker.docker_swarm_service:
    name: registry
    hostname: "{{registry_hostname}}"
    image: "{{registry_docker_image}}:{{registry_version}}"
    networks:
      - "{{traefik_network}}"
    mode: replicated
    force_update: yes
    restart_config:
      condition: on-failure
    env:
      REGISTRY_HTTP_ADDR: "0.0.0.0:{{registry_port}}"
      REGISTRY_HTTP_HOST: "registry.{{git_tld}}"
      REGISTRY_HTTP_DEBUG_ADDR: "0.0.0.0:{{registry_debug_port}}"
      REGISTRY_HTTP_DEBUG_PROMETHUS_ENABLED: "true"
      REGISTRY_HTTP_DEBUG_PROMETHUS_PATH: "/metrics"
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: "/var/lib/registry"
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
      REGISTRY_STORAGE_CACHE_BLOBDESCRIPTOR: "redis"
      REGISTRY_REDIS_ADDR: "{{redis_hostname}}:{{redis_port}}"
      REGISTRY_REDIS_PASSWORD: ""
      REGISTRY_REDIS_DB: "0"
      REGISTRY_HTTP_SECRET: "{{docker_registry_secret}}"
      REGISTRY_NOTIFICATIONS_ENDPOINTS: >
        - name: portus
          url: http://{{portus_hostname}}:{{portus_port}}/v2/webhooks/events
          timeout: 2000ms
          threshold: 5
          backoff: 1s
    placement:
      constraints:
        - node.id == {{greytalon_node_id}}
    replicas: 1
    mounts:
      - source: /greytalon/apps/portus/registry/
        target: /var/lib/registry/
        type: bind
    labels:
      traefik.http.routers.registry.entrypoints: "websecure"
      traefik.http.routers.registry.rule: "Host(`registry.{{git_tld}}`)"
      traefik.http.routers.registry.tls: "true"
      traefik.http.routers.registry.service: "registry"
      traefik.http.routers.registry.tls.certresolver: "{{default_certificate_resolver}}"
      traefik.http.services.registry.loadbalancer.server.port: "{{registry_port}}"
      traefik.enable: "true"
    state: present
  tags: registry