---
- name: Ensure Gitea Directories Exist
  when: inventory_hostname == ['redtalon'][0]
  ansible.builtin.file:
    path: /redtalon/apps/gitea
    mode: 0755
    state: directory
  tags: gitea

- name: Ensure Gitea DNS Records Exist
  ansible.builtin.import_tasks: roles/traefik/tasks/dreamhost.yml
  when: inventory_hostname == groups['managers'][0]
  vars:
    domain_name: "{{ gitea_domain }}"
  tags:
    - gitea
    - dns
  no_log: true

- name: Ensure Gitea Database exist
  ansible.builtin.import_tasks: roles/postgres/tasks/database_manager.yml
  when: inventory_hostname == groups['managers'][0]
  vars:
    database_name: "{{ gitea_database }}"
    database_user: "{{ gitea_database_user }}"
    database_password: "{{ gitea_database_password }}"
  tags: gitea
  no_log: true

- name: Deploy Gitea Service
  when: inventory_hostname == groups['managers'][0]
  community.docker.docker_swarm_service:
    name: gitea
    hostname: "{{ gitea_hostname }}"
    image: "{{ gitea_docker_image }}:{{ gitea_version }}"
    networks:
      - "{{ traefik_network }}"
    mode: replicated
    force_update: yes
    publish:
      - published_port: "2222"
        target_port: "22"
    restart_config:
      condition: on-failure
    env:
      GITEA__DEFAULT__RUN_USER: "{{ gitea_app_user }}"
      GITEA__DEFAULT__RUN_MODE: "prod"
      GITEA__repository.upload__ALLOWED_TYPES: ".zip,text/plain,image/*"
      GITEA__repository.release__ALLOWED_TYPES: ".zip,text/plain,image/*"
      GITEA__repository.upload__FILE_MAX_SIZE: "5"
      GITEA__repository.upload__MAX_FILES: "10"
      GITEA__server__PROTOCOL: "http"
      GITEA__server__DOMAIN: "{{ gitea_domain }}"
      GITEA__server__HTTP_ADDR: "0.0.0.0"
      GITEA__server__HTTP_PORT: "{{ gitea_port }}"
      GITEA__server__SSH_DOMAIN: "{{ gitea_domain }}"
      GITEA__server__SSH_PORT: "22"
      GITEA__security__REVERSE_PROXY_TRUSTED_PROXIES: "*"
      GITEA__database__DB_TYPE: "postgres"
      GITEA__database__HOST: "{{ postgres_hostname }}:{{ postgres_port }}"
      GITEA__database__NAME: "{{ gitea_database }}"
      GITEA__database__USER: "{{ gitea_database_user }}"
      GITEA__database__PASSWD: "{{ gitea_database_password }}"
      GITEA__database__SSL_MODE: "disable"
      GITEA__mailer__ENABLED: "true"
      GITEA__mailer__MAILER_PROTOCOL: "smtps"
      GITEA__mailer__SMTP_ADDR: "{{ email_host }}"
      GITEA__mailer__USER: "{{ email_user }}"
      GITEA__mailer__PASSWD: "{{ email_password }}"
      GITEA__mailer__FROM: "{{ email_user }}"
      GITEA__session__PROVIDER: "redis"
      GITEA__session__PROVIDER_CONFIG: "network=tcp,addr={{ redis_hostname }}:{{ redis_port }},db=0,pool_size=100,idle_timeout=180"
      GITEA__session__COOKIE_NAME: "{{ gitea_cookie_name }}"
      GITEA__session__COOKIE_SECURE: "false"
      GITEA__cache__ENABLED: "true"
      GITEA__cache__ADAPTER: "redis"
      GITEA__cache__HOST: "network=tcp,addr={{ redis_hostname }}:{{ redis_port }},db=0,pool_size=100,idle_timeout=180"
      GITEA_CUSTOM: "/data/gitea"
    placement:
      constraints:
        - node.id == {{ redtalon_node_id }}
    replicas: 1
    mounts:
      - source: /redtalon/apps/gitea/
        target: /data/
        type: bind
    labels:
      traefik.http.routers.gitea.entrypoints: "websecure"
      traefik.http.routers.gitea.rule: "Host(`{{ gitea_domain }}`)"
      traefik.http.routers.gitea.middlewares: "default-headers@file"
      traefik.http.routers.gitea.tls: "true"
      traefik.http.routers.gitea.service: "gitea"
      traefik.http.routers.gitea.tls.certresolver: "{{ default_certificate_resolver }}"
      traefik.http.services.gitea.loadbalancer.server.port: "{{ gitea_port }}"
      traefik.enable: "true"
    state: present
  tags: gitea

- name: Import Gitea Runner Role
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/runner.yml"
  tags: gitea