---
database_docker_image: "goharbor/harbor-db"
database_hostname: "harbor-db"
harbor_docker_image: "goharbor/harbor-core"
harbor_hostname: "harbor"
harbor_proxy_docker_image: "goharbor/nginx-photon"
harbor_proxy_hostname: "nginx"
harbor_version: "v2.6.0"
jobservice_docker_image: "goharbor/harbor-jobservice"
jobservice_hostname: "harbor-jobservice"
logging_docker_image: "goharbor/harbor-log"
logging_hostname: "harbor-log"
logging_port: "10514"
portal_docker_image: "goharbor/harbor-portal"
portal_hostname: "harbor-portal"
registry_docker_image: "goharbor/registry-photon"
registry_hostname: "registry"
registryctl_docker_image: "goharbor/harbor-registryctl"
registryctl_hostname: "registryctl"
trivy_docker_image: "goharbor/trivy-adapter-photon"
trivy_hostname: "trivy-adapter"