---
- name: Ensure FreshRSS Directory Exist
  file:
    path: "{{project_directory}}/freshrss"
    state: directory
  tags: freshrss

- import_tasks: roles/postgres/tasks/database_manager.yml
  vars:
    database_name: "{{freshrss_database}}"
    database_user: "{{freshrss_database_user}}"
    database_password: "{{freshrss_database_password}}"
  tags: freshrss
  no_log: true

- name: Create FreshRSS Docker Container
  community.general.docker_container:
    name: freshrss
    hostname: freshrss
    container_default_behavior: compatibility
    network_mode: default
    image: "linuxserver/freshrss:{{freshrss_version}}"
    pull: yes
    restart_policy: unless-stopped
    networks:
      - name: proxy
    networks_cli_compatible: yes
    comparisons:
      '*': strict
    state: started
    env:
      POSTGRES_DB: "{{freshrss_database}}"
      POSTGRES_USER: "{{freshrss_database_user}}"
      POSTGRES_PASSWORD: "{{freshrss_database_password}}"
    volumes:
      - "{{project_directory}}/freshrss:/config"
    labels:
      traefik.http.routers.freshrss.entrypoints: "websecure"
      traefik.http.routers.freshrss.tls: "true"
      traefik.http.routers.freshrss.rule: "Host(`rss.{{project_tld}}`)"
      traefik.http.routers.freshrss.service: "freshrss"
      traefik.http.services.freshrss.loadbalancer.server.port: "80"
      traefik.enable: "true"
  tags: freshrss

- import_tasks: "{{role_path}}/tasks/bridge.yml"
  tags:
    - freshrss