---
- name: Ensure FreshRSS DNS Records Exist
  ansible.builtin.import_tasks: roles/traefik/tasks/dns.yml
  when: inventory_hostname == groups['managers'][0]
  vars:
    domain_name: "{{ freshrss_domain }}"
  tags: freshrss
  no_log: true

- name: Ensure FreshRSS Dataset Exist
  when: inventory_hostname == groups['workers'][0]
  community.general.zfs:
    name: greytalon/apps/freshrss
    state: present
  tags: 
    - freshrss
    - zfs

- name: Ensure FreshRSS Database Exist
  ansible.builtin.import_tasks: roles/postgres/tasks/database_manager.yml
  when: inventory_hostname == groups['managers'][0]
  vars:
    database_name: "{{ freshrss_database }}"
    database_user: "{{ freshrss_database_user }}"
    database_password: "{{ freshrss_database_password }}"
  tags: freshrss
  no_log: true

- name: Deploy FreshRSS Service
  when: inventory_hostname == groups['managers'][0]
  community.docker.docker_swarm_service:
    name: freshrss
    hostname: "{{ freshrss_hostname }}"
    image: "{{ freshrss_docker_image }}:{{ freshrss_version }}"
    env:
      TZ: "{{ default_timezone }}"
    networks:
      - "{{ traefik_network }}"
    mode: replicated
    force_update: yes
    restart_config:
      condition: on-failure
    placement:
      constraints:
        - node.id == {{ greytalon_node_id }}
    replicas: 1
    mounts:
      - source: /greytalon/apps/freshrss/
        target: /config/
        type: bind
    labels:
      traefik.http.routers.freshrss.entrypoints: "websecure"
      traefik.http.routers.freshrss.rule: "Host(`{{ freshrss_domain }}`)"
      traefik.http.routers.freshrss.middlewares: "default-headers@file"
      traefik.http.routers.freshrss.tls: "true"
      traefik.http.routers.freshrss.service: "freshrss"
      traefik.http.routers.freshrss.tls.certresolver: "{{ default_certificate_resolver }}"
      traefik.http.services.freshrss.loadbalancer.server.port: "{{ freshrss_port }}"
      traefik.enable: "true"
    state: present
  tags: freshrss

- name: Import FreshRSS Bridge Role
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/bridge.yml"
  tags: freshrss
