---
- name: Log into Private Registry
  community.docker.docker_login:
    registry: "{{ registry_url }}"
    username: "{{ registry_username }}"
    password: "{{ registry_password }}"
    reauthorize: yes
  register: registry_state
  tags: always