---
- name: Ensure Homer Directory Exist
  file:
    path: "{{project_directory}}/homer"
    state: directory
  tags: homer

- name: Ensure Homer Configuration Files Exist
  template:
    src: config.yml.j2
    dest: "{{project_directory}}/homer/config.yml"
  tags: homer
  notify: restart homer
  no_log: true

- name: Create Homer Docker Container
  community.general.docker_container:
    name: homer
    image: "b4bz/homer:{{homer_version}}"
    pull: yes
    hostname: homer
    container_default_behavior: compatibility
    network_mode: default
    restart_policy: unless-stopped
    networks:
      - name: proxy
    networks_cli_compatible: yes
    state: started
    volumes:
      - "{{project_directory}}/homer:/www/assets"
    labels:
      traefik.http.routers.homer.entrypoints: "websecure"
      traefik.http.routers.homer.tls: "true"
      traefik.http.routers.homer.rule: "Host(`{{project_tld}}`,`www.{{project_tld}}`)"
      traefik.http.routers.homer.middlewares: "default-headers@file"
      traefik.http.routers.homer.service: "homer"
      traefik.http.services.homer.loadbalancer.server.port: "8080"
      traefik.enable: "true"
  tags: homer
