---
- name: Ensure Anime Media Dataset Exist
  when: inventory_hostname == groups['media'][0]
  community.general.zfs:
    name: blacktalon/media/anime
    state: present
  tags: 
    - sonarr-anime
    - zfs

- name: Ensure Anime Media Download Dataset Exist
  when: inventory_hostname == groups['media'][0]
  community.general.zfs:
    name: blacktalon/media/downloads/anime
    state: present
  tags: 
    - sonarr-anime
    - zfs

- name: Ensure Sonarr Anime Dataset Exist
  when: inventory_hostname == groups['media'][0]
  community.general.zfs:
    name: blacktalon/apps/sonarr2
    state: present
  tags: 
    - sonarr-anime
    - zfs

- name: Ensure Sonarr Anime DNS Records Exist
  ansible.builtin.import_tasks: roles/traefik/tasks/dns.yml
  when: inventory_hostname == groups['managers'][0]
  vars:
    domain_name: "{{ sonarr_anime_domain }}"
  tags: 
    - sonarr-anime
    - dns
  no_log: true

- name: Ensure Sonarr Anime Configuration Files Exist
  when: inventory_hostname == groups['media'][0]
  ansible.builtin.template:
    src: config-anime.xml.j2
    mode: 0644
    dest: "{{ project_root_directory }}/sonarr2/config.xml"
  tags: sonarr-anime
  no_log: true

- name: Deploy Sonarr Anime Service
  when: inventory_hostname == groups['managers'][0]
  community.docker.docker_swarm_service:
    name: sonarr_anime
    hostname: "{{ sonarr_anime_hostname }}"
    image: "{{ sonarr_docker_image }}:{{ sonarr_version }}"
    networks:
      - "{{ traefik_network }}"
    mode: replicated
    force_update: yes
    restart_config:
      condition: on-failure
    env:
      PUID: "{{ media_user }}"
      PGID: "{{ media_group }}"
      TZ: "{{ default_timezone }}"
      DOCKER_MODS: "gilbn/theme.park:{{ sonarr_hostname }}"
      TP_THEME: "{{ theme_park_default }}"
    placement:
      constraints:
        - node.id == {{ blacktalon_node_id }}
    replicas: 1
    mounts:
      - source: "/blacktalon/apps/sonarr2/"
        target: /config/
        type: bind
      - source: "{{ project_media_directory }}/anime/"
        target: /media/anime/
        type: bind
      - source: "{{ project_download_directory }}"
        target: /media/downloads/
        type: bind
    labels:
      traefik.http.routers.sonarr-anime.entrypoints: "websecure"
      traefik.http.routers.sonarr-anime.rule: "Host(`{{ sonarr_anime_domain }}`)"
      traefik.http.routers.sonarr-anime.middlewares: "default-headers@file,authelia@file"
      traefik.http.routers.sonarr-anime.tls: "true"
      traefik.http.routers.sonarr-anime.service: "sonarr-anime"
      traefik.http.routers.sonarr-anime.tls.certresolver: "{{ default_certificate_resolver }}"
      traefik.http.services.sonarr-anime.loadbalancer.server.port: "{{ sonarr_anime_port }}"
      traefik.enable: "true"
    state: present
  tags: sonarr-anime