---
- name: Ensure Hydra Directory Exist
  file:
    path: "{{project_directory}}/hydra"
    state: directory
    owner: "{{media_user}}"
    group: "{{media_group}}"
  tags: hydra

- name: Create Hydra Docker Container
  community.general.docker_container:
    name: hydra
    image: "linuxserver/hydra2:{{hydra_version}}"
    pull: yes
    hostname: hydra
    container_default_behavior: compatibility
    network_mode: default
    restart_policy: unless-stopped
    comparisons:
      labels: allow_more_present
      '*': strict
    networks:
      - name: proxy
    networks_cli_compatible: yes
    state: started
    env:
      PUID: "{{media_user}}"
      PGID: "{{media_group}}"
      TZ: "{{default_timezone}}"
    volumes:
      - "{{project_directory}}/hydra:/config"
      - "{{media_directory}}/downloads:/downloads"
    labels:
      traefik.http.routers.hydra.entrypoints: "websecure"
      traefik.http.routers.hydra.tls: "true"
      traefik.http.routers.hydra.rule: "Host(`hydra.{{project_tld}}`)"
      traefik.http.middlewares.hydra_rewrite_theme.plugin.rewritebody.rewrites.regex: "</head>"
      traefik.http.middlewares.hydra_rewrite_theme.plugin.rewritebody.rewrites.replacement: "<link rel=stylesheet type=text/css href=https://gilbn.github.io/theme.park/CSS/themes/nzbhydra2/{{theme_park_default}}.css></head>"
      traefik.http.routers.hydra.middlewares: "default-headers@file,hydra_rewrite_theme"
      traefik.http.routers.hydra.service: "hydra"
      traefik.http.services.hydra.loadbalancer.server.port: "5076"
      traefik.enable: "true"
  tags: hydra
