---
    - name: Restart Airsonic
      community.general.docker_container:
        name: airsonic
        container_default_behavior: compatibility
        restart: yes
      listen: restart airsonic
