---
- name: Restart Portus
  community.general.docker_container:
    name: portus
    container_default_behavior: compatibility
    restart: yes
  listen: restart portus

- name: Restart Registry
  community.general.docker_container:
    name: registry
    container_default_behavior: compatibility
    restart: yes
  listen: restart registry

- name: Restart Clair
  community.general.docker_container:
    name: clair
    container_default_behavior: compatibility
    restart: yes
  listen: restart clair
