---
- name: Restart FreshRSS
  community.general.docker_container:
    name: freshrss
    container_default_behavior: compatibility
    restart: yes
  listen: restart freshrss

- name: Restart RSS-Bridge
  community.general.docker_container:
    name: rssbridge
    container_default_behavior: compatibility
    restart: yes
  listen: restart rssbridge
