---
    - name: Restart Chow Down
      community.general.docker_container:
        name: chowdown
        container_default_behavior: compatibility
        restart: yes
      listen: restart chowdown
