---
- name: Install packages
  import_role:
    name: common_roles/install_latest
  vars:
    packages:
    - "docker"
    - "docker-compose"

- name: Start and enable docker
  become: true
  systemd:
    name: docker
    daemon_reload: true
    state: started
    enabled: true