---
- name: UFW Deny ALL except HTTP and HTTPS
  community.general.ufw:
    state: enabled
    policy: deny
    rule: allow
    port: "{{ item }}"
  with_items:
    - "{{ ports.http }}"
    - "{{ ports.https }}"

- name: UFW limit SSH Traffic
  community.general.ufw:
    state: enabled
    rule: limit
    port: "{{ ports.ssh }}"