---
- name: Restart Node Exporter
  community.general.docker_container:
    name: node-exporter
    container_default_behavior: compatibility
    restart: yes
  listen: restart node-exporter

- name: Restart Alert Manager
  community.general.docker_container:
    name: alertmanager
    container_default_behavior: compatibility
    restart: yes
  listen: restart alertmanager

- name: Restart Cadvisor
  community.general.docker_container:
    name: cadvisor
    container_default_behavior: compatibility
    restart: yes
  listen: restart cadvisor

- name: Restart Prometheus
  community.general.docker_container:
    name: prometheus
    container_default_behavior: compatibility
    restart: yes
  listen: restart prometheus

- name: Restart Grafana
  community.general.docker_container:
    name: grafana
    container_default_behavior: compatibility
    restart: yes
  listen: restart grafana
