---
- name: Ensure Tdarr Dataset Exist
  when: inventory_hostname == groups['media'][0]
  community.general.zfs:
    name: blacktalon/apps/tdarr
    state: present
  tags: tdarr

- name: Ensure Tdarr Directories Exist
  when: inventory_hostname == groups['media'][0]
  ansible.builtin.file:
    path: "{{ item }}"
    mode: 0755
    state: directory
  loop:
    - "{{ project_root_directory }}/tdarr/server"
    - "{{ project_root_directory }}/tdarr/config"
    - "{{ project_root_directory }}/tdarr/logs"
  tags: tdarr

- name: Install jsondiff Python library
  when: inventory_hostname == groups['managers'][0]
  become: true
  become_method: sudo
  ansible.builtin.pip:
    name: jsondiff
  tags: tdarr

- name: Create Tdarr Docker Compose File
  when: inventory_hostname == groups['media'][0]
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ project_root_directory }}/tdarr/docker-compose.yml"
    mode: 0775
  tags: tdarr

- name: Deploy Tdarr from Compose File
  when: inventory_hostname == groups['media'][0]
  community.docker.docker_compose:
    project_src: "{{ project_root_directory }}/tdarr/"
    files:
      - docker-compose.yml
    state: present
  tags: tdarr