---
- name: Ensure Tdarr Directory Exist
  when: inventory_hostname == groups['media'][0]
  ansible.builtin.file:
    path: "{{ project_root_directory }}/tdarr"
    mode: 0644
    state: directory
  tags: tdarr

- name: Ensure Tdarr Transcode Volume Exist
  when: inventory_hostname == groups['media'][0]
  community.docker.docker_volume:
    name: transcode
    state: present
  tags: tdarr

- name: Install jsondiff Python library
  when: inventory_hostname == groups['managers'][0]
  become: true
  become_method: sudo
  ansible.builtin.pip:
    name: jsondiff
  tags: tdarr

- name: Create Tdarr Docker Compose File
  when: inventory_hostname == groups['media'][0]
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ project_root_directory }}/tdarr/docker-compose.yml"
    mode: 0775
  tags: tdarr

- name: Deploy Tdarr from Compose File
  when: inventory_hostname == groups['media'][0]
  community.docker.docker_stack:
    state: present
    name: tdarr
    compose:
      - "{{ project_root_directory }}/tdarr/docker-compose.yml"
  tags: tdarr
