---
- name: Ensure Tdarr Dataset Exist
  when: inventory_hostname == groups['media'][0]
  community.general.zfs:
    name: blacktalon/apps/tdarr
    state: present
  tags:
    - tdarr
    - zfs

- name: Ensure Tdarr Directories Exist
  when: inventory_hostname == groups['media'][0]
  ansible.builtin.file:
    path: "{{ item.path }}"
    mode: "{{ item.mode }}"
    state: directory
  loop:
    - {path: '{{ project_root_directory }}/tdarr/server', mode: '0755'}
    - {path: '{{ project_root_directory }}/tdarr/config', mode: '0755'}
    - {path: '{{ project_root_directory }}/tdarr/logs', mode: '0755'}
  tags: tdarr

- name: Install jsondiff Python library
  when: inventory_hostname == groups['managers'][0]
  become: true
  become_method: ansible.builtin.sudo
  ansible.builtin.pip:
    name: jsondiff
  tags: tdarr

- name: Ensure Tdarr DNS Records Exist
  ansible.builtin.import_tasks: roles/traefik/tasks/dreamhost.yml
  when: inventory_hostname == groups['managers'][0]
  vars:
    domain_name: "{{ tdarr_domain }}"
  tags:
    - tdarr
    - dns
  no_log: true

- name: Create Tdarr Docker Compose File
  when: inventory_hostname == groups['media'][0]
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ project_root_directory }}/tdarr/docker-compose.yml"
    mode: 0775
  tags: tdarr

- name: Deploy Tdarr from Compose File
  when: inventory_hostname == groups['media'][0]
  community.docker.docker_compose:
    project_src: "{{ project_root_directory }}/tdarr/"
    pull: true
    files:
      - docker-compose.yml
    state: present
  tags: tdarr