---
- import_tasks: roles/postgres/tasks/database_manager.yml
  when: inventory_hostname == groups['managers'][0]
  vars:
    database_name: "{{ listmonk_database }}"
    database_user: "{{ listmonk_database_user }}"
    database_password: "{{ listmonk_database_password }}"
  tags: listmonk
  no_log: true

- name: Deploy Listmonk Service
  when: inventory_hostname == groups['managers'][0]
  community.docker.docker_swarm_service:
    name: listmonk
    hostname: "{{ listmonk_hostname }}"
    image: "{{ listmonk_docker_image }}:{{ listmonk_version }}"
    networks:
      - "{{ traefik_network }}"
    mode: global
    command: [sh, -c, "yes | ./listmonk --install && ./listmonk"]
    env:
      TZ: "{{ default_timezone }}"
      LISTMONK_app__address: "0.0.0.0:{{ listmonk_port }}"
      LISTMONK_app__admin_username: "{{ listmonk_admin_username }}"
      LISTMONK_app__admin_password: "{{ listmonk_admin_password }}"
      LISTMONK_db__host: "{{ postgres_hostname }}"
      LISTMONK_db__port: "{{ postgres_port }}"
      LISTMONK_db__user: "{{ listmonk_database_user }}"
      LISTMONK_db__password: "{{ listmonk_database_password }}"
      LISTMONK_db__database: "{{ listmonk_database }}"
      LISTMONK_db__ssl_mode: "disable"
    restart_config:
      condition: on-failure
    placement:
      constraints:
        - node.id == {{ yellowtalon_node_id }}
    labels:
      traefik.http.routers.listmonk.entrypoints: "websecure"
      traefik.http.routers.listmonk.rule: "Host(`listmonk.{{ project_tld }}`)"
      traefik.http.routers.listmonk.middlewares: "default-headers@file"
      traefik.http.routers.listmonk.tls: "true"
      traefik.http.routers.listmonk.service: "listmonk"
      traefik.http.routers.listmonk.tls.certresolver: "{{ default_certificate_resolver }}"
      traefik.http.services.listmonk.loadbalancer.server.port: "{{ listmonk_port }}"
      traefik.enable: "true"
    state: present
  tags: listmonk