---
clair_version: "v2.1.8"
portus_version: "head"
registry_version: "2.7"
portus_background_hostname: "portus_background"
clair_hostname: "portus_clair"
portus_hostname: "portus"
portus_port: "3000"
registry_hostname: "registry"
registry_port: "5000"
registry_debug_port: "5001"
clair_docker_image: "quay.io/coreos/clair"
portus_docker_image: "opensuse/portus"
registry_docker_image: "registry"