---
matrix_turn_secret: "{{vault_matrix_turn_secret}}"
matrix_registration_shared_secret: "{{vault_matrix_registration_shared_secret}}"
matrix_macaroon_secret_key: "{{vault_matrix_macaroon_secret_key}}"
matrix_form_secret: "{{vault_matrix_form_secret}}"
matrix_database_user: "synapse"
matrix_database_password: "{{vault_matrix_database_password}}"
matrix_database: "synapse"
matrix_coturn_turn_static_auth_secret: "{{vault_matrix_coturn_turn_static_auth_secret}}"
matrix_coturn_turn_external_ip_address: "{{vault_matrix_coturn_turn_external_ip_address}}"
ircbridge_database_user: "ircbridge"
ircbridge_database_password: "{{vault_ircbridge_database_password}}"
ircbridge_database: "ircbridge"
matrix_iecbridge_application_services_token: "{{vault_matrix_iecbridge_application_services_token}}"
matrix_iecbridge_homeserver_token: "{{vault_matrix_iecbridge_homeserver_token}}"