---
- name: Ensure PostgreSQL Databases are Present.
  community.general.postgresql_db:
    login_host: "{{ development_postgres_localhost }}"
    port: "{{ postgres_port }}"
    login_user: "{{ postgres_root_user }}"
    login_password: "{{ development_postgres_root_password }}"
    name: "{{ database_name }}"
    state: "present"

- name: Ensure PostgreSQL Users are Present.
  community.general.postgresql_user:
    login_host: "{{ development_postgres_localhost }}"
    port: "{{ postgres_port }}"
    login_user: "{{ postgres_root_user }}"
    login_password: "{{ development_postgres_root_password }}"
    name: "{{ database_user }}"
    password: "{{ database_password }}"
    state: "present"