---
- name: Init Wallabag Database
  community.docker.docker_container_exec:
    container: wallabag
    command: "docker exec wallabag /var/www/wallabag/bin/console wallabag:install --env=prod --no-interaction"
  register: result

- name: Create Admin User
  community.docker.docker_container_exec:
    container: wallabag
    command: "docker exec wallabag /var/www/wallabag/bin/console fos:user:create --super-admin --env=prod --no-interaction {{ wallabag_admin_user }} {{ project_notification_email }} {{ wallabag_admin_passwword }}"
  register: result

- name: Insure Admin User is Activated
  community.docker.docker_container_exec:
    container: wallabag
    command: "docker exec wallabag /var/www/wallabag/bin/console fos:user:activate {{ wallabag_admin_user }} -e prod"
  register: result

- name: Clear Wallabag Cache
  community.docker.docker_container_exec:
    container: wallabag
    command: "docker exec wallabag /var/www/wallabag/bin/console cache:clear -e prod"
  register: result